// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var $$Set = require("bs-platform/lib/js/set.js");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Int32 = require("bs-platform/lib/js/int32.js");
var Stream = require("bs-platform/lib/js/stream.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var IntSet = $$Set.Make([Int32.compare]);

var UnknownOperation = Caml_exceptions.create("One-Aoc2018.UnknownOperation");

function inputLines(param) {
  return $$Array.to_list(Fs.readFileSync("resources/one.txt", "utf8").split("\n"));
}

function lineToOperation(line) {
  return Caml_string.get(line, 0);
}

function lineToAmount(line) {
  var rangeEnd = line.length;
  return Caml_format.caml_int32_of_string($$String.sub(line, 1, rangeEnd - 1 | 0));
}

function lineToFrequencyChange(line) {
  return /* tuple */[
          Caml_string.get(line, 0),
          lineToAmount(line)
        ];
}

function applyFrequencyChange(total, change) {
  var operation = change[0];
  var exit = 0;
  switch (operation) {
    case 43 : 
        return total + change[1] | 0;
    case 44 : 
        exit = 1;
        break;
    case 45 : 
        return total - change[1] | 0;
    default:
      exit = 1;
  }
  if (exit === 1) {
    throw [
          UnknownOperation,
          "unknown operation: " + $$String.make(1, operation)
        ];
  }
  
}

function circularStream(l) {
  var length = List.length(l);
  return Stream.from((function (i) {
                return Js_primitive.some(List.nth(l, Caml_int32.mod_(i, length)));
              }));
}

function findFirstRepeatFrequency(l) {
  var changes = circularStream(l);
  var knownFrequencies = IntSet[/* empty */0];
  var frequency = Int32.zero;
  var $$break = false;
  while(!$$break) {
    frequency = applyFrequencyChange(frequency, Stream.next(changes));
    if (Curry._2(IntSet[/* mem */2], frequency, knownFrequencies)) {
      $$break = true;
    } else {
      knownFrequencies = Curry._2(IntSet[/* add */3], frequency, knownFrequencies);
    }
  };
  return frequency;
}

function processChanges(changes) {
  return List.fold_left(applyFrequencyChange, Int32.zero, changes);
}

function firstSolution(param) {
  var changes = List.map(lineToFrequencyChange, inputLines(/* () */0));
  return List.fold_left(applyFrequencyChange, Int32.zero, changes);
}

function secondSolution(param) {
  return findFirstRepeatFrequency(List.map(lineToFrequencyChange, inputLines(/* () */0)));
}

exports.IntSet = IntSet;
exports.UnknownOperation = UnknownOperation;
exports.inputLines = inputLines;
exports.lineToOperation = lineToOperation;
exports.lineToAmount = lineToAmount;
exports.lineToFrequencyChange = lineToFrequencyChange;
exports.applyFrequencyChange = applyFrequencyChange;
exports.circularStream = circularStream;
exports.findFirstRepeatFrequency = findFirstRepeatFrequency;
exports.processChanges = processChanges;
exports.firstSolution = firstSolution;
exports.secondSolution = secondSolution;
/* IntSet Not a pure module */
